# Generated by Django 4.0.1 on 2022-01-14 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
